env : development

development :
  databases :
    - name : eid_security
      hosts : 
        - host : 127.0.0.1
          port : 27017
      dbname : eid_security_dev
      slaveOk : false
    - name : eid_data
      hosts :
        - host : 127.0.0.1
          port : 27017
      dbname : eid_data_dev
      slaveOk : false
test :
  databases :
    - name : eid_security
      hosts : 
        - host : localhost
      dbname : eid_security_test
    - name : eid_data
      hosts :
        - host : localhost
          port : 27017
      dbname : eid_data_test
      slaveOk : false
production :
  databases :
    - name : eid_security
      hosts : 
        - host : localhost
      dbname : eid_security
      user : eid
      password : p@ssw0rd        
    - name : eid_data
      hosts :
        - host : localhost
          port : 27017
      dbname : eid_data
      slaveOk : false